trigger:
  branches:
    include:
      - "master"
    exclude:
      - "feature/*"
      - "feat/*"
      - "fix/*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: '0'
  minor: '1'
  revision: $[counter(variables['minor'], 1)]

steps:
- script: echo v$(major).$(minor).$(revision)
  displayName: 'Tag this version of master'