trigger:
  branch: master

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: '0'
  minor: '0'
  revision: $[counter(variables['minor'], 1)]

steps:
- script: echo v$(major).$(minor).$(revision)
  displayName: 'Tag this version of master'