trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    steps:
    - script: |
        cd $(Build.Repository.LocalPath)
        terraform init -no-color -backend=false
      displayName: Run Terraform init

    - script: terraform validate -no-color
      displayName: Run Terraform validate
  
  - job: Unit_and_Integration
    steps:
    - script: |
        sudo apt update 
        sudo apt install -y --no-install-recommends go-dep
      displayName: Update system and install Dep
    - script: |
        echo $GOPATH
        go env
      displayName: Show environment variables
    - script: |
        mkdir -p /home/vsts/go/src
        mv $(Build.Repository.LocalPath) /home/vsts/go/src
        cd /home/vsts/go/src
        ls -al
        dep ensure
      displayName: Making sure all dependecies have been fulfiled
    - script: go test -v ./tests/ -timeout 20m
      displayName: Run Go Test