trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    steps:
    - script: |
        cd $(Build.Repository.LocalPath)
        terraform init -no-color -backend=false
      displayName: Run Terraform init

    - script: terraform validate -no-color
      displayName: Run Terraform validate