trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    steps:
    - script: |
        cd $(Build.Repository.LocalPath)
        terraform init -no-color -backend=false
      displayName: Run Terraform init

    - script: terraform validate -no-color
      displayName: Run Terraform validate
  
  - job: Unit_and_Integration
    steps:
    - script: sudo apt-get update && sudo apt-get install -y --no-install-recommends go-dep
      displayName: Update system and install Dep
    - script: dep ensure
      displayName: Making sure all dependecies have been fulfiled
    - script: go test -v ./tests/ -timeout 20m