trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    steps:
    - script: |
        cd $(Build.Repository.LocalPath)
        terraform init -no-color -backend=false
      displayName: Run Terraform init

    - script: terraform validate -no-color
      displayName: Run Terraform validate
  
  - job: Unit_and_Integration
    steps:
    - script: |
        sudo apt update 
        sudo apt install -y --no-install-recommends go-dep
      displayName: Update system and install Dep
    - script: |
        echo $GOPATH
        go env
      displayName: Show environment variables
    - script: |
        mkdir -p /home/vsts/go/src/tf-vmss
        mv $(Build.Repository.LocalPath)/* /home/vsts/go/src/tf-vmss
        cd /home/vsts/go/src/tf-vmss
        ls -al
        dep ensure
      displayName: Making sure all dependecies have been fulfiled
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Professional'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_CLIENT_ID="$env:servicePrincipalId"
          export ARM_CLIENT_SECRET="$env:servicePrincipalKey"
          export ARM_TENANT_ID="$env:tenantId"
          export ARM_SUBSCRIPTION_ID="$(az account show --query 'id' -o tsv)"
          go test -v /home/vsts/go/src/tf-vmss/tests/ -timeout 20m
      displayName: Run Go Test