trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform Validate
  jobs:
  - job: Validate
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.Repository.LocalPath)/'
        commandOptions: '-no-color -backend=false'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(Build.Repository.LocalPath)/'
        commandOptions: '-no-color'